name: Delete All Releases & Tags
on:
  workflow_dispatch:
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Delete all releases and tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Deleting all releases..."
          # Delete published releases
          releases=$(gh release list --json tagName --jq '.[].tagName' 2>/dev/null || echo "")
          if [ -n "$releases" ]; then
            echo "$releases" | while read tag; do
              [ -n "$tag" ] && gh release delete "$tag" --yes
            done
          fi
          
          # Delete draft releases
          draft_releases=$(gh release list --draft --json tagName --jq '.[].tagName' 2>/dev/null || echo "")
          if [ -n "$draft_releases" ]; then
            echo "$draft_releases" | while read tag; do
              [ -n "$tag" ] && gh release delete "$tag" --yes
            done
          fi
          
          echo "Deleting all tags..."
          tags=$(git tag -l)
          if [ -n "$tags" ]; then
            echo "$tags" | while read tag; do
              [ -n "$tag" ] && git push origin --delete "refs/tags/$tag"
            done
          else
            echo "No tags found"
          fi
          
          echo "Done!"
