name: Delete All Releases & Tags

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Delete all releases and tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Deleting all releases..."
          gh release list --limit 100 | tail -n +2 | cut -f1 | grep -v "^$" | xargs -r -I {} gh release delete {} --yes || echo "No releases to delete"
          
          echo "Deleting all tags..."
          git tag | xargs -r -I {} git push origin --delete refs/tags/{} || echo "No tags to delete"
          
          echo "Done!"
