name: Delete All Releases & Tags
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: sudo apt-get install -y gh jq

      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          repo="${GITHUB_REPOSITORY}"
          per_page=100
          page=1
          while :; do
            releases_json=$(gh api "repos/${repo}/releases?per_page=${per_page}&page=${page}" 2>/dev/null || echo "[]")
            count=$(echo "$releases_json" | jq 'length')
            [ "$count" -eq 0 ] && break
            echo "$releases_json" | jq -r '.[] | [.id, .tag_name] | @tsv' | while IFS=$'\t' read -r rid tag; do
              gh api --method DELETE "repos/${repo}/releases/${rid}" || true
              [ -n "$tag" ] && git push origin --delete "refs/tags/$tag" || true
            done
            page=$((page + 1))
          done

          git fetch --tags --force
          tags=$(git tag -l)
          if [ -n "$tags" ]; then
            echo "$tags" | while read -r tag; do
              [ -n "$tag" ] && git push origin --delete "refs/tags/$tag" || true
            done
            git tag -d $(git tag -l) || true
          fi
