name: Update Index Page

on:
  schedule:
    # Chạy mỗi 5 phút
    - cron: '*/5 * * * *'
  workflow_dispatch: # Cho phép chạy thủ công

jobs:
  update-index:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update index.html with latest versions
      shell: powershell
      run: |
        # Lấy danh sách releases từ GitHub
        Write-Host "Fetching GitHub releases..."
        try {
            $githubReleases = Invoke-RestMethod -Uri "https://api.github.com/repos/bibicadotnet/microsoft-edge-multi-portable/releases" -Headers @{
                "User-Agent" = "GitHub-Actions"
            }
        } catch {
            Write-Host "Error fetching GitHub releases: $_"
            exit 1
        }
        
        Write-Host "Found $($githubReleases.Count) releases"
        
        # Tạo HTML content cho từng channel
        $channels = @(
            @{ Name = "Stable"; Pattern = "edge-stable-portable"; Display = "Microsoft Edge Stable" },
            @{ Name = "Beta"; Pattern = "edge-beta-portable"; Display = "Microsoft Edge Beta" },
            @{ Name = "Dev"; Pattern = "edge-dev-portable"; Display = "Microsoft Edge Developer" },
            @{ Name = "Canary"; Pattern = "edge-canary-portable"; Display = "Microsoft Edge Canary" }
        )
        
        $versionHtml = ""
        
        foreach ($channel in $channels) {
            # Tìm release mới nhất cho channel này
            $channelReleases = $githubReleases | Where-Object { 
                $_.tag_name -like "*$($channel.Pattern)*" 
            } | Sort-Object published_at -Descending
            
            if ($channelReleases.Count -gt 0) {
                $latestRelease = $channelReleases[0]
                
                # Extract version từ tag name
                # Tag format: edge-stable-portable-x64_139.0.3405.86_2024-12-19T10-00-03Z
                $versionMatch = $latestRelease.tag_name -match "x64_([0-9.]+)_"
                $version = if ($versionMatch) { $matches[1] } else { "Unknown" }
                
                # Tìm file zip trong assets
                $zipAsset = $latestRelease.assets | Where-Object { $_.name -like "*.zip" }
                
                if ($zipAsset) {
                    $downloadUrl = $zipAsset.browser_download_url
                    $versionHtml += @"
                    <li class="version-item">
                        <div>
                            <div class="version-name">$($channel.Display)</div>
                            <a href="$downloadUrl" class="download-link" target="_blank">Download ZIP</a>
                        </div>
                        <div class="version-number">$version</div>
                    </li>
"@
                } else {
                    $versionHtml += @"
                    <li class="version-item">
                        <div>
                            <div class="version-name">$($channel.Display)</div>
                            <span class="unavailable">No ZIP found</span>
                        </div>
                        <div class="version-number">$version</div>
                    </li>
"@
                }
            } else {
                $versionHtml += @"
                    <li class="version-item">
                        <div>
                            <div class="version-name">$($channel.Display)</div>
                            <span class="unavailable">Not available yet</span>
                        </div>
                        <div class="version-number">-</div>
                    </li>
"@
            }
        }
        
        # Đọc file index.html hiện tại
        if (-not (Test-Path "index.html")) {
            Write-Host "index.html not found!"
            exit 1
        }
        
        $indexContent = Get-Content "index.html" -Raw -Encoding UTF8
        
        # Thay thế phần versions
        $startMarker = "<!-- AUTO_UPDATE_START -->"
        $endMarker = "<!-- AUTO_UPDATE_END -->"
        
        $startIndex = $indexContent.IndexOf($startMarker)
        $endIndex = $indexContent.IndexOf($endMarker)
        
        if ($startIndex -eq -1 -or $endIndex -eq -1) {
            Write-Host "Cannot find version markers in index.html"
            exit 1
        }
        
        # Tính toán vị trí
        $beforeContent = $indexContent.Substring(0, $startIndex + $startMarker.Length)
        $afterContent = $indexContent.Substring($endIndex)
        
        # Tạo nội dung mới
        $newIndexContent = $beforeContent + "`r`n" + $versionHtml + "`r`n                    " + $afterContent
        
        # Cập nhật thời gian
        $timeStartMarker = "<!-- AUTO_UPDATE_TIME_START -->"
        $timeEndMarker = "<!-- AUTO_UPDATE_TIME_END -->"
        
        $timeStartIndex = $newIndexContent.IndexOf($timeStartMarker)
        $timeEndIndex = $newIndexContent.IndexOf($timeEndMarker)
        
        if ($timeStartIndex -ne -1 -and $timeEndIndex -ne -1) {
            $currentTime = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss UTC")
            $beforeTime = $newIndexContent.Substring(0, $timeStartIndex + $timeStartMarker.Length)
            $afterTime = $newIndexContent.Substring($timeEndIndex)
            $newIndexContent = $beforeTime + "`r`n            Last updated: $currentTime`r`n            " + $afterTime
        }
        
        # Ghi file
        Set-Content "index.html" -Value $newIndexContent -Encoding UTF8 -NoNewline
        
        Write-Host "index.html updated successfully"
        Write-Host "Version information:"
        $channels | ForEach-Object {
            $channelName = $_.Name
            $channelReleases = $githubReleases | Where-Object { 
                $_.tag_name -like "*$($_.Pattern)*" 
            } | Sort-Object published_at -Descending
            
            if ($channelReleases.Count -gt 0) {
                $versionMatch = $channelReleases[0].tag_name -match "x64_([0-9.]+)_"
                $version = if ($versionMatch) { $matches[1] } else { "Unknown" }
                Write-Host "  $channelName : $version"
            } else {
                Write-Host "  $channelName : Not available"
            }
        }

    - name: Check for changes and commit
      shell: powershell
      run: |
        # Configure git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Check if there are changes
        git add index.html
        
        $changes = git diff --cached --name-only
        if ([string]::IsNullOrEmpty($changes)) {
            Write-Host "No changes to commit"
        } else {
            Write-Host "Changes detected, committing..."
            $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss UTC"
            git commit -m "Update index page with latest versions - $timestamp"
            git push
            Write-Host "Changes committed and pushed"
        }
